kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-fe95cb6-35
  - docker.io/opsmx11/oes-audit-service:argo-dc95660-10
  - docker.io/opsmx11/oes-platform:argo-bbcc4962-65
  - docker.io/opsmx11/oes-dashboard:argo-978978f-12
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-7
  - docker.io/opsmx11/gate:argo-4b2e8daa-7
  - docker.io/opsmx11/sapor:argo-24da5291a1fc1b90967935baec98ad3910b02fad-23
  - docker.io/opsmx11/oes-autopilot:argo-4ae3eb67b-27
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
