kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-8472268-34
  - docker.io/opsmx11/oes-audit-service:argo-4a69860-6
  - docker.io/opsmx11/oes-platform:argo-36da73a3-33
  - docker.io/opsmx11/oes-dashboard:argo-9425db0-9
  - docker.io/opsmx11/oes-visibility:argo-f493c0d-6
  - docker.io/opsmx11/gate:argo-c175444c-2
  - docker.io/opsmx11/sapor:argo-f294d8eddebd52d877f4b77a44d7f1946c974195-15
  - docker.io/opsmx11/oes-autopilot:argo-4df232e26-3
  - docker.io/opsmx11/oes-datascience:argo-b041824813d3446b4b8ae3a111dcbc62300c2a7f-3
