kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-54e0d8c-41
  - docker.io/opsmx11/oes-audit-service:argo-dc95660-10
  - docker.io/opsmx11/oes-platform:argo-d47a0ec1-86
  - docker.io/opsmx11/oes-dashboard:argo-b363cb0-19
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-7
  - docker.io/opsmx11/gate:argo-4b2e8daa-7
  - docker.io/opsmx11/sapor:argo-1ae80a0f97e94913e4e750f0e623a29f3833db2b-31
  - docker.io/opsmx11/oes-autopilot:argo-6dfd51f58-34
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
