kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-8472268-34
  - docker.io/opsmx11/oes-audit-service:argo-dc95660-10
  - docker.io/opsmx11/oes-platform:argo-37acf92c-39
  - docker.io/opsmx11/oes-dashboard:argo-ee85fba-11
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-7
  - docker.io/opsmx11/gate:argo-1a89b895-3
  - docker.io/opsmx11/sapor:argo-f294d8eddebd52d877f4b77a44d7f1946c974195-15
  - docker.io/opsmx11/oes-autopilot:argo-507397cd2-5
  - docker.io/opsmx11/oes-datascience:argo-507397cd2c74f1a55ca6a6cfa12fa859a090859f-5
