kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-8472268-34
  - docker.io/opsmx11/oes-audit-service:argo-dc95660-10
  - docker.io/opsmx11/oes-platform:argo-13617433-64
  - docker.io/opsmx11/oes-dashboard:argo-978978f-12
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-7
  - docker.io/opsmx11/gate:argo-1a89b895-3
  - docker.io/opsmx11/sapor:argo-a26d6f912f81177037a8e7b2c413e66fea981951-17
  - docker.io/opsmx11/oes-autopilot:argo-500acc087-24
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
