kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-54e0d8c-41
  - docker.io/opsmx11/oes-audit-service:argo-dc95660-10
  - docker.io/opsmx11/oes-platform:argo-854f392b-84
  - docker.io/opsmx11/oes-dashboard:argo-b363cb0-19
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-7
  - docker.io/opsmx11/gate:argo-4b2e8daa-7
  - docker.io/opsmx11/sapor:argo-3369b376ef30180a45bcb2b6ad47777c10427b2c-29
  - docker.io/opsmx11/oes-autopilot:argo-6dfd51f58-34
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
