kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-fe95cb6-36
  - docker.io/opsmx11/oes-audit-service:argo-dc95660-10
  - docker.io/opsmx11/oes-platform:argo-bbcc4962-65
  - docker.io/opsmx11/oes-dashboard:argo-978978f-12
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-7
  - docker.io/opsmx11/gate:argo-4b2e8daa-7
  - docker.io/opsmx11/sapor:argo-4746594ca9575a843fdca0fcbe8f080f3162469b-24
  - docker.io/opsmx11/oes-autopilot:argo-cc3b7ecb6-28
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
