kustomize:
  images:
  - docker.io/opsmx11/oes-audit-client:argo-32fae11-47
  - docker.io/opsmx11/oes-audit-service:argo-16f08e7-11
  - docker.io/opsmx11/oes-platform:argo-d47a0ec1-91
  - docker.io/opsmx11/oes-dashboard:argo-b363cb0-19
  - docker.io/opsmx11/oes-visibility:argo-42b5bae-8
  - docker.io/opsmx11/gate:argo-91603f88-8
  - docker.io/opsmx11/sapor:argo-385a6989ec0b97a9c9d83ceb7a432f7089b77bf6-32
  - docker.io/opsmx11/oes-autopilot:argo-6d8f24988-48
  - docker.io/opsmx11/oes-datascience:argo-beb86ec33f46e253de0107437c0625f0481147d5-8
